name: StreetPhare CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze-and-test:
    name: Analyse & Tests Flutter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: get dependencies
        run: flutter clean && flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Verify Dart SDK constraint
        run: dart --version

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Static analysis
        run: dart analyze

      - name: Run tests
        run: flutter test
